import "./globals.css";
import { Epilogue } from "next/font/google";
import { Providers } from "@/providers/Providers";

const epilogue = Epilogue({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={` ${epilogue.className} bg-gray-100`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
