import AuthProvider from "@/providers/AuthProvider";
import "./globals.css";
import { Epilogue } from "next/font/google";
import ToasterProvider from "@/providers/ToasterProvider";

const epilogue = Epilogue({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={` bg-gray-100`}>
        <ToasterProvider />
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
