import DesktopSidebar from "@/components/sidebar/DesktopSidebar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <main className="w-[80%] ml-auto">
          <DesktopSidebar />
          {children}
        </main>
      </body>
    </html>
  );
}
